class AppImage{
  // static const appLogo="assets/images/applogo.png";

  static const logOutLogo="assets/images/logout.png";
  static const splashImage="assets/images/reserveThree.png";
  static const restaurant="assets/images/restaurant.png";
  static const restaurantTwo="assets/images/restaurantIcon.png";
  static const restaurantThree="assets/images/restaurantThree.png";
  static const restaurantEdit="assets/images/restaurantEdit.jpeg";
  static const addRestaurant="assets/images/addRestaurant.png";
  static const home="assets/images/home.png";
  static const map="assets/images/map.png";
  static const mapTwo="assets/images/mapTwo.png";
  static const appointment="assets/images/appointment.png";
  // static const booking="assets/images/booking.png";
  // static const bookingTwo="assets/images/bookingTwo.png";
  static const histroy="assets/images/history.png";
  static const histroyTwo="assets/images/historyTwo.png";
  static const user="assets/images/user.png";
  static const evaluation="assets/images/evaluation.png";
  static const prioritize="assets/images/prioritize.png";
  static const yes="assets/images/yes.png";
  static const yesno="assets/images/yesno.png";
  static const yesnoTwo="assets/images/yesnoTwo.png";
  static const yesnoThree="assets/images/yesnoThree.png";
  static const r1="assets/images/r1.png";
  static const dish="assets/images/dish.png";
  static const dishTwo="assets/images/dishTwo.png";
  static const colorDish="assets/images/colorDish.png";
  static const rest1="assets/images/rest1.jpeg";
  static const rest2="assets/images/rest2.jpeg";
  static const website="assets/images/website.png";
  static const profile="assets/images/profile.png";
  static const userOutline="assets/images/userOutline.png";
  static const yesGreen="assets/images/yesGreen.png";
  static const noRed="assets/images/noRed.png";
  static const greenYes="assets/images/greenYes.png";
  static const redNo="assets/images/redNo.png";
}